GET http://localhost:3000/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzE3NTIzMTAyLCJleHAiOjE3MTc1MjY3MDJ9.u6GfWmlDXwytT2azqvzRA441vtuKaqmxDDUPneP8uNc
